import ProjectLayout from '../../components/ProjectLayout';
import SmartLink from '../../components/SmartLink';

export default function WebPlanner() {
  return (
    <ProjectLayout
      title="Web Planner"
      description="A personal planning app with an interactive calendar, task management, and auto-saving daily notes. FastAPI + SQLAlchemy backend, React 19 + TypeScript frontend, and PostgreSQL running in Docker."
      badge="Full-Stack"
      tags={['Python', 'FastAPI', 'SQLAlchemy', 'Alembic', 'React', 'TypeScript', 'PostgreSQL', 'Docker']}
      githubUrl="https://github.com/Nick-Trigger/Web-Planner"
    >
      <h2>Overview</h2>

      <p>
        Web Planner is a personal planning app built around a full calendar view. Month and year
        navigation opens any day into a detail view where tasks and notes for that date live side
        by side. It is a complete full-stack application: a typed REST API, a relational schema
        managed by migrations, and a modern React frontend.
      </p>

      <h3>Features</h3>

      <ul>
        <li>
          <strong>Calendar.</strong> Month/year navigation with a full calendar grid; click any day
          to open its detail view.
        </li>
        <li>
          <strong>Tasks.</strong> Create tasks with a due date/time and priority (normal / medium /
          high), mark them done or delete them. Tasks appear on their calendar day.
        </li>
        <li>
          <strong>Daily notes.</strong> Per-date freeform notes with auto-save.
        </li>
        <li>
          <strong>US holidays.</strong> Fetched from the nager.at public API and displayed on the
          calendar.
        </li>
      </ul>

      <hr />

      <h2>Tech Stack</h2>

      <table>
        <thead>
          <tr>
            <th>Layer</th>
            <th>Technologies</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <strong>Backend</strong>
            </td>
            <td>
              Python 3.12, FastAPI, SQLAlchemy 2.0, Alembic migrations, managed with{' '}
              <code>uv</code>
            </td>
          </tr>
          <tr>
            <td>
              <strong>Frontend</strong>
            </td>
            <td>React 19 + TypeScript (React Compiler), built with Vite</td>
          </tr>
          <tr>
            <td>
              <strong>Styling</strong>
            </td>
            <td>Tailwind CSS + daisyUI</td>
          </tr>
          <tr>
            <td>
              <strong>Database</strong>
            </td>
            <td>PostgreSQL 16 running in Docker</td>
          </tr>
          <tr>
            <td>
              <strong>Dev workflow</strong>
            </td>
            <td>
              <code>dev.ps1</code> one-command startup: Postgres, backend, and frontend in Windows
              Terminal tabs
            </td>
          </tr>
        </tbody>
      </table>

      <hr />

      <h2>Architecture</h2>

      <p>
        The backend follows a clean layered structure: <code>models.py</code> holds the SQLAlchemy
        ORM models, <code>schemas.py</code> the Pydantic request/response shapes, and{' '}
        <code>routers/</code> the API endpoints. Settings load from a <code>.env</code> file via{' '}
        <code>pydantic-settings</code>, and FastAPI auto-generates interactive Swagger and ReDoc
        documentation for the whole API.
      </p>

      <p>A few deliberate decisions:</p>

      <ul>
        <li>
          <strong>Migrations read the database URL from <code>.env</code>, not{' '}
          <code>alembic.ini</code>.</strong> <code>alembic/env.py</code> injects the URL at runtime,
          keeping credentials out of committed files.
        </li>
        <li>
          <strong>Autogenerated migrations stay honest.</strong> <code>alembic/env.py</code>{' '}
          imports <code>app.models</code> so every model registers with{' '}
          <code>Base.metadata</code> — the thing Alembic's autogenerate actually scans.
        </li>
        <li>
          <strong>React Compiler is enabled.</strong> Components are auto-memoized at build time,
          so the frontend is written as idiomatic React with no manual{' '}
          <code>useMemo</code>/<code>useCallback</code> noise.
        </li>
      </ul>

      <hr />

      <h2>Developer Experience</h2>

      <p>
        The whole stack boots with a single command. <code>.\dev.ps1</code> starts Postgres
        (detached), then opens the FastAPI backend and the Vite frontend in separate Windows
        Terminal tabs. A <code>-DbOnly</code> flag brings up just the database for running backend
        tests, and <code>-Stop</code> tears everything down. Backend tests run under{' '}
        <code>pytest</code> via <code>uv</code>.
      </p>

      <p>
        The project grew out of my{' '}
        <SmartLink to="/projects/fastapi-react-starter">FastAPI + React starter template</SmartLink>, which
        packages this same stack and workflow as a reusable GitHub template.
      </p>
    </ProjectLayout>
  );
}
